#!/usr/bin/env bash
# script to display information about subdomains

display ()
{
    printf "The subdomain %s is a " "$2"
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
    printf " record and points to "
    dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
    echo ""
}

if [ -z "$2" ]; then
    for sub in "www" "lb-01" "web-01" "web-02"
    do
	display "$1" "$sub"
    done
else
    display "$1" "$2"
fi
