#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# configure output
sudo echo "Hello World!" > /var/www/html/index.html

# start engine
sudo service nginx start
