#!/usr/bin/env bash
# Install nginx
sudo apt-get update -y
sudo apt-get install nginx -y

# change owner to current user to write
sudo chown -R "$USER":"$USER" /var/www/html/
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/

# configure output
echo "Hello World!" | sudo tee /var/www/html/index.html

# update config file to redirect
sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;" /etc/nginx/sites-available/default

# start engine or restart
sudo service nginx restart
