#!/usr/bin/env bash
# A script that displays "To infinity and beyond" indefinitely
# Creates the file /var/run/myscript.pid containing its PID
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving
# a SIGQUIT or SIGTERM signal

sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'

trap "echo I hate the Kill command; rm -rf /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'; exit" SIGINT
trap "sudo rm /var/run/myscript.pid; exit" SIGQUIT

i=1
while [ "$i" -lt 2 ]; do
    echo "To infinity and beyond";
    sleep 2
done
