#!/usr/bin/env bash
# A script that displays "To infinity and beyond" indefinitely
# Displays "I am invincible!!!" when receiving a SIGTERM signal

trap "echo I am invincible!!!" SIGTERM
i=1
while [ "$i" -lt 2 ]; do
    echo "To infinity and beyond";
    sleep 2
done
