#!/usr/bin/env bash
# This script prints "Best School" 10 times using the while loop
i=0;
while [ "$i" -lt 10 ]; do
    i=$(( i + 1 ));
    if [ "$i" -eq 4 ];
    then
        echo "bad luck";
    elif [ "$i" -eq 8 ];
    then
        echo "good luck";
    else
        echo "Best School";
    fi
done
