#!/usr/bin/env bash
# This script prints a clock for 12hrs 59 mins
i=0;
while [ "$i" -lt 13 ]; do
    echo "Hour: $i";
    j=1;
    while [ "$j" -lt 60 ]; do
        echo "$j"
        j=$(( j + 1 ))
    done
    i=$(( i + 1));
done
