#!/usr/bin/env bash
# A script that resolves localhost to 127.0.0.2 and facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.edit
echo "127.0.0.2		localhost" > ~/hosts.edit
echo "8.8.8.8		facebook.com" >> ~/hosts.edit
cp -f ~/hosts.edit /etc/hosts
