#!/usr/bin/env bash
# runs nginx as non root user
sudo chown -R nginx:nginx /var/www/html
chmod 750 /etc/nginx/nginx.conf
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
sudo -H -u nginx bash -c "service nginx start"
